services:
  qlever:
    image: adfreiburg/qlever:latest
    container_name: icc-uvv-qlever
    ports:
      - "7011:7011"
    volumes:
      - qlever_data:/data
    restart: unless-stopped

volumes:
  qlever_data:
